package com.lilyle.lotus.model;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "Customers")
/*@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)*/
public class Customers {
    
    @Id
    @Column(name = "customerId", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long customerId;
    
    @Column(name = "customerName")
    private String customerName;
    
    @Column(name = "phoneNumber")
    private String phoneNumber;
    
    @Column(name = "address")
    private String address;
    
    @Column(name = "email")
    private String email;
    
    @Column(name = "goldmember")
    private int goldmember;
    
    @Column(name = "password")
    private String password;
    
    @Column(name = "buyingNumber")
    private int buyingNumber;

    @OneToMany(orphanRemoval=true, cascade=CascadeType.REMOVE)
    private Set<Stocks> stocks;
    
    public Customers() {
    }

    public Customers(long customerId, String customerName, String phoneNumber, String address, int goldmember,
            String password, int buyingNumber) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.goldmember = goldmember;
        this.password = password;
        this.buyingNumber = buyingNumber;
    }

    public Customers(long customerId, String customerName, String phoneNumber, String address, String email,
            int goldmember, String password, int buyingNumber) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.email = email;
        this.goldmember = goldmember;
        this.password = password;
        this.buyingNumber = buyingNumber;
    }


    public long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getGoldmember() {
        return this.goldmember;
    }

    public void setGoldmember(int goldmember) {
        this.goldmember = goldmember;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getBuyingNumber() {
        return this.buyingNumber;
    }

    public void setBuyingNumber(int buyingNumber) {
        this.buyingNumber = buyingNumber;
    }

}
