package com.lilyle.lotus.model;
// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

    private String productId;
    private String productName;
    private long productPrice;
    private String productDescription;

    public Products() {
    }

    public Products(String productId, String productName, long productPrice) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
    }

    public Products(String productId, String productName, long productPrice, String productDescription) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productDescription = productDescription;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public long getProductPrice() {
        return this.productPrice;
    }

    public void setProductPrice(long productPrice) {
        this.productPrice = productPrice;
    }

    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

}
