package com.lilyle.lotus.model;

import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products")
public class Products implements java.io.Serializable {
    
    
    @Id
    @Column(name = "productId", nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long productId;
    
    @Column(name = "productName")
    private String productName;
    
    @Column(name = "productPrice")
    private long productPrice;
    
    @Column(name = "productDescription")
    private String productDescription;
    
    /*@OneToMany(cascade=CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name="productId")
    private Set<Stocks> stocks;*/
    
    public Products() {
    }

    public Products(long productId, String productName, long productPrice) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
    }

    public Products(long productId, String productName, long productPrice, String productDescription) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productDescription = productDescription;
    }

    
    /*public Products(long productId, String productName, long productPrice, String productDescription,
            Set<Stocks> stocks) {
        super();
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productDescription = productDescription;
        this.stocks = stocks;
    }

    public Set<Stocks> getStocks() {
        return stocks;
    }

    public void setStocks(Set<Stocks> stocks) {
        this.stocks = stocks;
    }
*/
    public long getProductId() {
        return this.productId;
    }

    public void setProductId(long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public long getProductPrice() {
        return this.productPrice;
    }

    public void setProductPrice(long productPrice) {
        this.productPrice = productPrice;
    }

    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

}
