package com.lilyle.lotus.model;
// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stocks generated by hbm2java
 */
@Entity
@Table(name = "Stocks")
public class Stocks implements java.io.Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "stockId", unique = true, nullable = false)
    private String stockId;
    
/*    @ManyToOne
    private Products product;*/
    
    @Column(name = "numberInStock")
    private Integer numberInStock;
    
    public String getStockId() {
        return stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public Integer getNumberInStock() {
        return this.numberInStock;
    }

    public void setNumberInStock(Integer numberInStock) {
        this.numberInStock = numberInStock;
    }

/*    public Products getProduct() {
        return product;
    }

    public void setProduct(Products product) {
        this.product = product;
    }*/
}
