package com.lilyle.lotus.model;
// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

/**
 * StocksId generated by hbm2java
 */
public class StocksId implements java.io.Serializable {

    private String stockId;
    private String productId;

    public StocksId() {
    }

    public StocksId(String stockId, String productId) {
        this.stockId = stockId;
        this.productId = productId;
    }

    public String getStockId() {
        return this.stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof StocksId))
            return false;
        StocksId castOther = (StocksId) other;

        return ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
                && castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())))
                && ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
                        && castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
        result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
        return result;
    }

}
