package com.lilyle.lotus.model;
// Generated Jun 5, 2018 2:55:00 PM by Hibernate Tools 5.1.7.Final

/**
 * Stocks generated by hbm2java
 */
public class Stocks implements java.io.Serializable {

    private StocksId id;
    private Integer numberInStock;

    public Stocks() {
    }

    public Stocks(StocksId id) {
        this.id = id;
    }

    public Stocks(StocksId id, Integer numberInStock) {
        this.id = id;
        this.numberInStock = numberInStock;
    }

    public StocksId getId() {
        return this.id;
    }

    public void setId(StocksId id) {
        this.id = id;
    }

    public Integer getNumberInStock() {
        return this.numberInStock;
    }

    public void setNumberInStock(Integer numberInStock) {
        this.numberInStock = numberInStock;
    }

}
